events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Замени "vk-clone" на имя своего репозитория
        location /vk-old-react-ts-zustand {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /vk-old-react-ts-zustand/index.html;
        }

        # Редирект с корня, чтобы при заходе на http://localhost:8080 бросало куда надо
        location / {
            return 301 $scheme://$http_host/vk-old-react-ts-zustand/;
        }
    }
}